name: Release Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: microsoft/setup-msbuild@v2

      - name: Build
        run: |
          msbuild Mochi.sln ^
            /m ^
            /p:Configuration=Release ^
            /p:Platform=x86

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            **/Release/*.dll
            **/Release/*.pdb